# Diccionario de clientes
MAPA_CLIENTES_VENDEDORES = {
    "Aguilar Cristian Fabian y Nocenti Sergio Hernan": "FRAIRE",
    "Arnaudo Matias Gonzalo": "FRAIRE",
    "AVERSA FACUNDO": "GIUSTA",
    "BARCO SEBASTIAN FERNANDO": "GIUSTA",
    "BRACO Y PORTA SA": "FRAIRE",
    "Bursztyn Gerardo Daniel":"GIUSTA",
    "CHIAVERANO GORGO SANTIAGO": "GIUSTA",
    "CAVALLERO DIEGO ALBERTO": "FRAIRE",
    "Crespo Angelo Matías": "FRAIRE",
    "Conde Jesica Elizabeth": "FRAIRE",
    "David Rosental e Hijos": "FRAIRE",
    "Dean Guillermo Horacio": "FRAIRE",
    "DISTRIBUIDORA OGGIER SRL":"FRAIRE",
    "FANG MEIJIN": "GIUSTA",
    "Fabian Alfredo Faccioli": "FRAIRE",
    "Ferreyra Rebeca Ruth": "FRAIRE",
    "GAGLIANO MARIA EMILIA Y GAGLIANO NICOLAS LUIS": "FRAIRE",
    "Genero Zunilda Isabel Norma": "FRAIRE",
    "GIRARDI WALTER ANTONIO": "FRAIRE",
    "Gonzales Matías Federico": "FRAIRE",
    "HUANG XIAOMEI": "GIUSTA",
    "HUANG ZHI": "GIUSTA",
    "INOCENTI CARLOS": "GIUSTA",
    "LIN XUEMEI": "GIUSTA",
    "Lisi Cesar Augusto": "FRAIRE",
    "MANUEL SANTIAGO": "GIUSTA",
    "MORONI LEANDRO OSCAR": "GIUSTA",
    "Paduan Carolina Beatriz": "FRAIRE",
    "Persoglia Gonzalo Eduardo": "FRAIRE",
    "Provincias Unidas Cooperativa de provision para comerciantes de vivienda y credito limitada": "FRAIRE",
    "RED VITAL AGRUPACIÓN": "FRAIRE",
    "San Javier distribuidora de alimentos S.R.L.": "FRAIRE",
    "SFP SA": "GIUSTA",
    "Toloza Juan Ramon": "GIUSTA",
    "VARGAS FIGUEROA SANTIAGO ALBERTO": "GIUSTA",
    "WANG FENGLAN": "GIUSTA",
    "WANG JINSHAN": "GIUSTA",
    "WENG ZHIHUI": "GIUSTA",
    "Wuang Lu": "GIUSTA",
    'Yaccuzzi Distribuciones Srl': "FRAIRE",
    "ZHENG YUANGONG": "GIUSTA"
}
